import Script from 'next/script'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@/assets/style/exports.scss'
import '../../public/common/commonlogin.css'
import reportWebVitals from '@/modules/utils/reportWebVitals'
//IE
import 'core-js/stable'
import 'react-app-polyfill/ie11'
import 'react-app-polyfill/ie9'
import 'react-app-polyfill/stable'
import 'regenerator-runtime/runtime'
// import ReactQueryProviders from '@/stores/react-query-provider';
import Hydration from '@/stores/hydration'
import LoginIframe from '@/component/LoginIframe'
import ListenerEvent from '@/component/ListenerEvent'
import { cookies } from 'next/headers'
import { selectProduct, setCookieData } from '@/api/serverAction'
import ReactQueryProviders from '@/stores/query-provider'
import { Product } from '../../golo'
import { useBearStore } from '@/stores/zustandStore'
const inter = Inter({ subsets: ['latin'] })
/**
 * html header metadata data setting
 * */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  applicationName: process.env.NEXT_PUBLIC_URL
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const zustandStore: number = useBearStore.getState().bears
  console.log('zustandStore', zustandStore)
  // const addBears = useBearStore((state) => state.increaseBears)
  // useBearStore.getState().increaseBears()
  const cookieStore = cookies()
  const theme = cookieStore.get('bear-store')
  // cookieStore.set('cookiescookiescookiescookiescookies', 'lee')
  // setCookieData()
  const data: Product[] = await selectProduct()
  return (
    <html lang="ko">
      <body className={inter.className}>
        {/* react query init start */}
        <Hydration />
        {/* <ReactQueryProviders isDark={true}>{children}</ReactQueryProviders> */}
        {children}
{/*         <LoginIframe open={true} /> */}
{/*         <ListenerEvent /> */}
      </body>

      {/* 운영에 경우 네이버 멥 openapi 실행 */}
      {process.env.NEXT_PUBLIC_RENDER_TYPE === 'production' && (
        <Script
          type="text/script"
          src="https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=t59m2wx9ow&submodules=geocoder"
        />
      )}
      {/* Jquery lib 주입 */}
      <Script type="text/script" src="/common/jquery-1.10.2.min.js" />
      {/* 메인 박스 로그인 공퉁 스크립트 주입 */}
      <Script type="text/script" src="https://www.ibkbox.net/ui/static_m/js/commonBox.js" />
    </html>
  )
}
reportWebVitals()
